import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/layouts/header";
import ReactQueryProvider from "@/hooks/ReactQueryProvider";
import NextTopLoader from "nextjs-toploader";
import ContextProvider from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRYPTO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#14161A" }} className={inter.className}>
        <NextTopLoader />
        <ReactQueryProvider>
          <ContextProvider>
            <Header />
            {children}
          </ContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
